# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]

# Add application configuration variables here, as shown below.
#

# app basics
WEBAPP_NAME: EXAMPLE APP
WEBAPP_DEFAULT_URL: localhost:3000
WEBAPP_DOMAIN: example.com

# default admin user
ADMIN_NAME: Joe Admin
ADMIN_EMAIL: admin@example.com
ADMIN_PASSWORD: changeme

# roles the webapp supports
ROLES: [admin, staff, user]

# SMTP settings
SMTP_ADDRESS: smtp.example.com
SMTP_PORT: 587
SMTP_AUTHENTICATION: login
SMTP_USER_NAME: example
SMTP_PASSWORD: password
SMTP_DEFAULT_FROM_ADDRESS: robot@example.com
SMTP_DEFAULT_REPLY_TO_ADDRESS: no-reply@example.com